#!/bin/sh

current_branch=`git rev-parse --abbrev-ref HEAD`
if [[ $current_branch = "master" || $current_branch = "main" || $current_branch = "dev" ]]; then
    message="Please don't commit directly to $current_branch."
    echo -e "\033[1;31mERROR: $message\033[0m";
    exit 1
fi
branch_name=$(git branch | grep '*' | sed 's/* //')
ticket_name=${branch_name#*/}
ticket_id=${ticket_name%/*}

valid_branch_regex="^(feature|fix|hotfix)\/${ticket_id}+\/.*$|^Release\/.*$"

message="There is something wrong with your branch name. You should rename your branch to a valid name and try again."
branch_length=${#branch_name}

max_length_message="Length of branch is more than 40 characters"

if [[ $branch_length > 40 ]]
then 
    echo "$max_length_message"
    exit 1
fi
    
if [[ ! $branch_name =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0