name: github-actions-template

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  static-check:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #Setup task
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run checks
        run: task runChecks

  test:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #Setup task
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run tests
        run: task runTests

  build:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #Setup task
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run build
        run: task runBuild

  deploy:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #Setup task
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run deployment
        run: task runDeploy
